# site settings
title: Portfolio
subtitle: by Stephen Urena
email: stephenmurena@gmail.com
description: I'm a Front-End Web Developer,  with experience in Agile software development. <br /> 
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 
city: San Diego
state: CA
zip_code: 
country: United States of America
phone: (619)387-5609

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/stephenurena
gitlab_url: https://gitlab.com/stephenmurena
googleplus_url: 
instagram_url: https://instagram.com/stephenurena
linkedin_url: https://www.linkedin.com/in/stephenmurena/
pinterest_url:
slack_url:
twitter_url: https://twitter.com/smurena

# build settings
markdown: kramdown

sass:
  style: compressed
